// Package brimstone provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.2 DO NOT EDIT.
package brimstone

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/labstack/echo/v4"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Error defines model for Error.
type Error struct {
	Code    int32  `json:"code"`
	Message string `json:"message"`
}

// Hash defines model for Hash.
type Hash struct {
	Hash string `gorm:"primaryKey" json:"hash"`
	Name string `gorm:"primaryKey" json:"name"`
}

// HashBatch defines model for HashBatch.
type HashBatch struct {
	Hashes   []Hash `gorm:"many2many:safename_hashes;References:name,hash" json:"hashes"`
	Safename string `gorm:"primaryKey" json:"safename"`
}

// HashesPutJSONBody defines parameters for HashesPut.
type HashesPutJSONBody = []HashBatch

// CyberArkPAMCPMEventPutJSONBody defines parameters for CyberArkPAMCPMEventPut.
type CyberArkPAMCPMEventPutJSONBody = []HashBatch

// HashesPutJSONRequestBody defines body for HashesPut for application/json ContentType.
type HashesPutJSONRequestBody = HashesPutJSONBody

// CyberArkPAMCPMEventPutJSONRequestBody defines body for CyberArkPAMCPMEventPut for application/json ContentType.
type CyberArkPAMCPMEventPutJSONRequestBody = CyberArkPAMCPMEventPutJSONBody

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// HashesPutWithBody request with any body
	HashesPutWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	HashesPut(ctx context.Context, body HashesPutJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// SendFullHashesGet request
	SendFullHashesGet(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// SendHashPrefixesGet request
	SendHashPrefixesGet(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CyberArkPAMCPMEventPutWithBody request with any body
	CyberArkPAMCPMEventPutWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CyberArkPAMCPMEventPut(ctx context.Context, body CyberArkPAMCPMEventPutJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GitGuardianEventPost request
	GitGuardianEventPost(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) HashesPutWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewHashesPutRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) HashesPut(ctx context.Context, body HashesPutJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewHashesPutRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) SendFullHashesGet(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewSendFullHashesGetRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) SendHashPrefixesGet(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewSendHashPrefixesGetRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CyberArkPAMCPMEventPutWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCyberArkPAMCPMEventPutRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CyberArkPAMCPMEventPut(ctx context.Context, body CyberArkPAMCPMEventPutJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCyberArkPAMCPMEventPutRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GitGuardianEventPost(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGitGuardianEventPostRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewHashesPutRequest calls the generic HashesPut builder with application/json body
func NewHashesPutRequest(server string, body HashesPutJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewHashesPutRequestWithBody(server, "application/json", bodyReader)
}

// NewHashesPutRequestWithBody generates requests for HashesPut with any type of body
func NewHashesPutRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/hashes")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PUT", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewSendFullHashesGetRequest generates requests for SendFullHashesGet
func NewSendFullHashesGetRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/hashes/sendhashes")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewSendHashPrefixesGetRequest generates requests for SendHashPrefixesGet
func NewSendHashPrefixesGetRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/hashes/sendprefixes")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCyberArkPAMCPMEventPutRequest calls the generic CyberArkPAMCPMEventPut builder with application/json body
func NewCyberArkPAMCPMEventPutRequest(server string, body CyberArkPAMCPMEventPutJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCyberArkPAMCPMEventPutRequestWithBody(server, "application/json", bodyReader)
}

// NewCyberArkPAMCPMEventPutRequestWithBody generates requests for CyberArkPAMCPMEventPut with any type of body
func NewCyberArkPAMCPMEventPutRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/notify/cybrcpmevent")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PUT", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGitGuardianEventPostRequest generates requests for GitGuardianEventPost
func NewGitGuardianEventPostRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/notify/ggevent")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// HashesPutWithBodyWithResponse request with any body
	HashesPutWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*HashesPutResponse, error)

	HashesPutWithResponse(ctx context.Context, body HashesPutJSONRequestBody, reqEditors ...RequestEditorFn) (*HashesPutResponse, error)

	// SendFullHashesGetWithResponse request
	SendFullHashesGetWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*SendFullHashesGetResponse, error)

	// SendHashPrefixesGetWithResponse request
	SendHashPrefixesGetWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*SendHashPrefixesGetResponse, error)

	// CyberArkPAMCPMEventPutWithBodyWithResponse request with any body
	CyberArkPAMCPMEventPutWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CyberArkPAMCPMEventPutResponse, error)

	CyberArkPAMCPMEventPutWithResponse(ctx context.Context, body CyberArkPAMCPMEventPutJSONRequestBody, reqEditors ...RequestEditorFn) (*CyberArkPAMCPMEventPutResponse, error)

	// GitGuardianEventPostWithResponse request
	GitGuardianEventPostWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GitGuardianEventPostResponse, error)
}

type HashesPutResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *string
	JSON401      *string
	JSONDefault  *Error
}

// Status returns HTTPResponse.Status
func (r HashesPutResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r HashesPutResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type SendFullHashesGetResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *string
	JSON401      *string
	JSONDefault  *Error
}

// Status returns HTTPResponse.Status
func (r SendFullHashesGetResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r SendFullHashesGetResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type SendHashPrefixesGetResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *string
	JSON401      *string
	JSONDefault  *Error
}

// Status returns HTTPResponse.Status
func (r SendHashPrefixesGetResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r SendHashPrefixesGetResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type CyberArkPAMCPMEventPutResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *string
	JSON401      *string
	JSONDefault  *Error
}

// Status returns HTTPResponse.Status
func (r CyberArkPAMCPMEventPutResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CyberArkPAMCPMEventPutResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GitGuardianEventPostResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *string
	JSON401      *string
	JSONDefault  *Error
}

// Status returns HTTPResponse.Status
func (r GitGuardianEventPostResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GitGuardianEventPostResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// HashesPutWithBodyWithResponse request with arbitrary body returning *HashesPutResponse
func (c *ClientWithResponses) HashesPutWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*HashesPutResponse, error) {
	rsp, err := c.HashesPutWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseHashesPutResponse(rsp)
}

func (c *ClientWithResponses) HashesPutWithResponse(ctx context.Context, body HashesPutJSONRequestBody, reqEditors ...RequestEditorFn) (*HashesPutResponse, error) {
	rsp, err := c.HashesPut(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseHashesPutResponse(rsp)
}

// SendFullHashesGetWithResponse request returning *SendFullHashesGetResponse
func (c *ClientWithResponses) SendFullHashesGetWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*SendFullHashesGetResponse, error) {
	rsp, err := c.SendFullHashesGet(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseSendFullHashesGetResponse(rsp)
}

// SendHashPrefixesGetWithResponse request returning *SendHashPrefixesGetResponse
func (c *ClientWithResponses) SendHashPrefixesGetWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*SendHashPrefixesGetResponse, error) {
	rsp, err := c.SendHashPrefixesGet(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseSendHashPrefixesGetResponse(rsp)
}

// CyberArkPAMCPMEventPutWithBodyWithResponse request with arbitrary body returning *CyberArkPAMCPMEventPutResponse
func (c *ClientWithResponses) CyberArkPAMCPMEventPutWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CyberArkPAMCPMEventPutResponse, error) {
	rsp, err := c.CyberArkPAMCPMEventPutWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCyberArkPAMCPMEventPutResponse(rsp)
}

func (c *ClientWithResponses) CyberArkPAMCPMEventPutWithResponse(ctx context.Context, body CyberArkPAMCPMEventPutJSONRequestBody, reqEditors ...RequestEditorFn) (*CyberArkPAMCPMEventPutResponse, error) {
	rsp, err := c.CyberArkPAMCPMEventPut(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCyberArkPAMCPMEventPutResponse(rsp)
}

// GitGuardianEventPostWithResponse request returning *GitGuardianEventPostResponse
func (c *ClientWithResponses) GitGuardianEventPostWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GitGuardianEventPostResponse, error) {
	rsp, err := c.GitGuardianEventPost(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGitGuardianEventPostResponse(rsp)
}

// ParseHashesPutResponse parses an HTTP response from a HashesPutWithResponse call
func ParseHashesPutResponse(rsp *http.Response) (*HashesPutResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &HashesPutResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest string
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest string
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseSendFullHashesGetResponse parses an HTTP response from a SendFullHashesGetWithResponse call
func ParseSendFullHashesGetResponse(rsp *http.Response) (*SendFullHashesGetResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &SendFullHashesGetResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest string
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest string
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseSendHashPrefixesGetResponse parses an HTTP response from a SendHashPrefixesGetWithResponse call
func ParseSendHashPrefixesGetResponse(rsp *http.Response) (*SendHashPrefixesGetResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &SendHashPrefixesGetResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest string
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest string
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseCyberArkPAMCPMEventPutResponse parses an HTTP response from a CyberArkPAMCPMEventPutWithResponse call
func ParseCyberArkPAMCPMEventPutResponse(rsp *http.Response) (*CyberArkPAMCPMEventPutResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CyberArkPAMCPMEventPutResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest string
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest string
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseGitGuardianEventPostResponse parses an HTTP response from a GitGuardianEventPostWithResponse call
func ParseGitGuardianEventPostResponse(rsp *http.Response) (*GitGuardianEventPostResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GitGuardianEventPostResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest string
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest string
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Add new hashes
	// (PUT /v1/hashes)
	HashesPut(ctx echo.Context) error
	// Trigger brimstone to send full hmsl-hashes to HMSL
	// (GET /v1/hashes/sendhashes)
	SendFullHashesGet(ctx echo.Context) error
	// Trigger brimstone to send hash prefixes to HMSL
	// (GET /v1/hashes/sendprefixes)
	SendHashPrefixesGet(ctx echo.Context) error
	// CyberArk PAM CPM Event
	// (PUT /v1/notify/cybrcpmevent)
	CyberArkPAMCPMEventPut(ctx echo.Context) error
	// Gitguardian event posted from webhooks
	// (POST /v1/notify/ggevent)
	GitGuardianEventPost(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// HashesPut converts echo context to params.
func (w *ServerInterfaceWrapper) HashesPut(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.HashesPut(ctx)
	return err
}

// SendFullHashesGet converts echo context to params.
func (w *ServerInterfaceWrapper) SendFullHashesGet(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.SendFullHashesGet(ctx)
	return err
}

// SendHashPrefixesGet converts echo context to params.
func (w *ServerInterfaceWrapper) SendHashPrefixesGet(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.SendHashPrefixesGet(ctx)
	return err
}

// CyberArkPAMCPMEventPut converts echo context to params.
func (w *ServerInterfaceWrapper) CyberArkPAMCPMEventPut(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CyberArkPAMCPMEventPut(ctx)
	return err
}

// GitGuardianEventPost converts echo context to params.
func (w *ServerInterfaceWrapper) GitGuardianEventPost(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GitGuardianEventPost(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.PUT(baseURL+"/v1/hashes", wrapper.HashesPut)
	router.GET(baseURL+"/v1/hashes/sendhashes", wrapper.SendFullHashesGet)
	router.GET(baseURL+"/v1/hashes/sendprefixes", wrapper.SendHashPrefixesGet)
	router.PUT(baseURL+"/v1/notify/cybrcpmevent", wrapper.CyberArkPAMCPMEventPut)
	router.POST(baseURL+"/v1/notify/ggevent", wrapper.GitGuardianEventPost)

}
