{
    "openapi": "3.0.3",
    "servers": [
        {
            "url": "https://api.gitguardian.com"
        }
    ],
    "info": {
        "title": "GitGuardian API (WITH LOCAL FIXES)",
        "version": "1.1.0",
        "termsOfService": "https://www.gitguardian.com/legal-terms",
        "license": {
            "name": "GitGuardian",
            "url": "https://www.gitguardian.com/legal-terms"
        },
        "x-logo": {
            "url": "https://static.gitguardian.com/Logo-blue.png",
            "altText": "GitGuardian"
        },
        "contact": {
            "name": "GitGuardian",
            "email": "support@gitguardian.com",
            "url": "https://www.gitguardian.com"
        },
        "description": "\n# Introduction\n\nWhether you want to build a complete integration with your software development\nworkflow or simply want to test GitGuardian's policy break detection on any text content,\nyou can use our API.\n\n- The base url for the latest version is `api.gitguardian.com/v1` over `HTTPS`.\n- All data is sent and received as JSON by default.\n- All timestamps returned are ISO-8601 compliant, example:\n```python\n2020-03-16T04:46:00+00:00 # for date-time\n```\n\nGitGu[...]"
    },
    "tags": [
        {
            "name": "API Tokens",
            "description": "Manage API tokens.\n"
        },
        {
            "name": "Secret Incidents",
            "description": "Manage incidents found by post-receive hooks on your GitGuardian Dashboard.\n"
        },
        {
            "name": "Secret Occurrences",
            "description": "Manage occurrences found by post-receive hooks on your GitGuardian Dashboard.\n"
        },
        {
            "name": "Secret Incident Notes",
            "description": "Manage notes on incidents found by post-receive hooks on your GitGuardian Dashboard.\n"
        },
        {
            "name": "Secret Detectors",
            "description": "Retrieve details on detectors used for secret detection.\n"
        },
        {
            "name": "Invitations",
            "description": "Manage workspace invitations.\n"
        },
        {
            "name": "Sources",
            "description": "Retrieve details on sources monitored by GitGuardian.\n"
        },
        {
            "name": "Members",
            "description": "Retrieve details about workspace members.\n"
        },
        {
            "name": "Scan Methods",
            "description": "Use GitGuardian's brain at your leisure.\n\nScanning API allows you to scan any content you want using GitGuardian's secrets detection algorithms.\n"
        },
        {
            "name": "Quota",
            "description": "Retrieve details about quota usage.\n"
        },
        {
            "name": "IaC scan methods",
            "description": "Scanning a directory for Infrastructure as Code (IaC) vulnerabilities allows\nyou to enhance security in your project configuration.\n"
        },
        {
            "name": "Audit logs",
            "description": "List of audit logs of the workspace.\n"
        },
        {
            "name": "Status",
            "description": "Check the status of the API and the overall system health.\n"
        },
        {
            "name": "Teams",
            "description": "Manage teams.\n"
        },
        {
            "name": "Team Invitations",
            "description": "Manage team invitations.\n"
        },
        {
            "name": "Team Memberships",
            "description": "Add or remove members from teams, or update their permissions.\n"
        },
        {
            "name": "Honeytokens",
            "description": "Manage honeytokens.\n"
        },
        {
            "name": "SCA",
            "description": "Software Composition Analysis\n"
        },
        {
            "name": "Honeytoken Notes",
            "description": "Manage notes on honeytokens.\n"
        },
        {
            "name": "Honeytokens Events",
            "description": "Manage events on honeytokens.\n"
        },
        {
            "name": "Honeytoken Sources",
            "description": "Manage sources on honeytokens.\n"
        },
        {
            "name": "Labels",
            "description": "Manage labels for honeytokens. Labels provide a flexible way to organize honeytokens. You can create your own labels in the form of keys and values, assign them to honeytokens, and use them to filter and search for honeytokens based on specific characteristics.\n"
        }
    ],
    "x-tagGroups": [
        {
            "name": "Tokens management",
            "tags": [
                "API Tokens"
            ]
        },
        {
            "name": "Incidents Management",
            "tags": [
                "Secret Incidents",
                "Secret Occurrences",
                "Secret Incident Notes"
            ]
        },
        {
            "name": "Honeytokens Management",
            "tags": [
                "Honeytokens",
                "Honeytokens Events",
                "Honeytoken Notes",
                "Honeytoken Sources",
                "Labels"
            ]
        },
        {
            "name": "Perimeter Management",
            "tags": [
                "Sources"
            ]
        },
        {
            "name": "User Management",
            "tags": [
                "Members",
                "Invitations"
            ]
        },
        {
            "name": "Secrets Scanning",
            "tags": [
                "Scan Methods",
                "Secret Detectors",
                "Quota"
            ]
        },
        {
            "name": "SCA",
            "tags": [
                "SCA"
            ]
        },
        {
            "name": "IaC Scanning",
            "tags": [
                "IaC Scan Methods"
            ]
        },
        {
            "name": "Team Management",
            "tags": [
                "Teams",
                "Team Invitations",
                "Team Memberships",
                "Team Requests",
                "Team Sources"
            ]
        },
        {
            "name": "Audit Logs",
            "tags": [
                "Audit Logs"
            ]
        },
        {
            "name": "Other",
            "tags": [
                "Status"
            ]
        }
    ],
    "paths": {
        "/v1/api_tokens/self": {
            "get": {
                "tags": [
                    "API Tokens"
                ],
                "operationId": "self-retrieve-api-token",
                "summary": "Retrieve details of the current API token."
            },
            "delete": {
                "tags": [
                    "API Tokens"
                ],
                "operationId": "self-delete-api-token",
                "summary": "Revoke the current API token."
            }
        },
        "/v1/api_tokens": {
            "get": {
                "tags": [
                    "API Tokens"
                ],
                "operationId": "list-api-tokens",
                "summary": "List API tokens.",
                "description": "List all the tokens in the workspace, some filters are available and described \nbelow.\n",
                "security": [
                    {
                        "APIKey": [
                            "api_tokens:read"
                        ]
                    }
                ]
            }
        },
        "/v1/api_tokens/{token_id}": {
            "get": {
                "tags": [
                    "API Tokens"
                ],
                "operationId": "retrieve-api-token",
                "summary": "Retrieve details of an API token.",
                "security": [
                    {
                        "APIKey": [
                            "api_tokens:read"
                        ]
                    }
                ]
            },
            "delete": {
                "tags": [
                    "API Tokens"
                ],
                "operationId": "delete-api-token",
                "summary": "Revoke an an API token.",
                "security": [
                    {
                        "APIKey": [
                            "api_tokens:write"
                        ]
                    }
                ]
            }
        },
        "/v1/auth/jwt": {
            "post": {
                "tags": [
                    "API Tokens"
                ],
                "operationId": "public-jwt-create",
                "summary": "Create a JSON Web Token.",
                "description": "Create a short lived JWT for authentication to specific GitGuardian services,\nincluding HasMySecretLeaked.\n"
            }
        },
        "/v1/incidents/secrets": {
            "get": {
                "tags": [
                    "Secret Incidents"
                ],
                "operationId": "list-incidents",
                "summary": "List secret incidents",
                "description": "List secret incidents detected by the GitGuardian dashboard.\nOccurrences are not returned in this route.\n",
                "security": [
                    {
                        "APIKey": [
                            "incidents:read"
                        ]
                    }
                ]
            }
        },
        "/v1/incidents/secrets/{incident_id}": {
            "get": {
                "tags": [
                    "Secret Incidents"
                ],
                "operationId": "retrieve-incidents",
                "summary": "Retrieve a secret incident",
                "description": "Retrieve secret incident detected by the GitGuardian dashboard with\nits occurrences.\n",
                "security": [
                    {
                        "APIKey": [
                            "incidents:read"
                        ]
                    }
                ]
            },
            "patch": {
                "tags": [
                    "Secret Incidents"
                ],
                "operationId": "update-secret-incident",
                "summary": "Update a secret incident",
                "description": "Update a secret incident\n",
                "security": [
                    {
                        "APIKey": [
                            "incidents:write"
                        ]
                    }
                ]
            }
        },
        "/v1/incidents/secrets/{incident_id}/leaks": {
            "get": {
                "tags": [
                    "Secret Incidents"
                ],
                "operationId": "retrieve-incidents-leaks",
                "summary": "Retrieve where a secret has been publicly leaked",
                "description": "Retrieve where a secret has been publicly leaked.\n",
                "security": [
                    {
                        "APIKey": [
                            "incidents:read"
                        ]
                    }
                ]
            }
        },
        "/v1/incidents/secrets/{incident_id}/assign": {
            "post": {
                "tags": [
                    "Secret Incidents"
                ],
                "operationId": "assign-incident",
                "summary": "Assign a secret incident",
                "description": "Assign secret incident detected by the GitGuardian dashboard to a workspace member\nby email.\n",
                "security": [
                    {
                        "APIKey": [
                            "incidents:write"
                        ]
                    }
                ]
            }
        },
        "/v1/incidents/secrets/{incident_id}/unassign": {
            "post": {
                "tags": [
                    "Secret Incidents"
                ],
                "operationId": "unassign-incident",
                "summary": "Unassign a secret incident",
                "description": "Unassign secret incident from a workspace member by email.\n",
                "security": [
                    {
                        "APIKey": [
                            "incidents:write"
                        ]
                    }
                ]
            }
        },
        "/v1/incidents/secrets/{incident_id}/resolve": {
            "post": {
                "tags": [
                    "Secret Incidents"
                ],
                "operationId": "resolve-incident",
                "summary": "Resolve a secret incident",
                "description": "Resolve a secret incident detected by the GitGuardian dashboard.\n",
                "security": [
                    {
                        "APIKey": [
                            "incidents:write"
                        ]
                    }
                ]
            }
        },
        "/v1/incidents/secrets/{incident_id}/ignore": {
            "post": {
                "tags": [
                    "Secret Incidents"
                ],
                "operationId": "ignore-incident",
                "summary": "Ignore a secret incident",
                "description": "Ignore a secret incident detected by the GitGuardian dashboard.\n",
                "security": [
                    {
                        "APIKey": [
                            "incidents:write"
                        ]
                    }
                ]
            }
        },
        "/v1/incidents/secrets/{incident_id}/reopen": {
            "post": {
                "tags": [
                    "Secret Incidents"
                ],
                "operationId": "reopen-incident",
                "summary": "Reopen a secret incident",
                "description": "Unresolve or unignore a secret incident detected by the GitGuardian dashboard.\n",
                "security": [
                    {
                        "APIKey": [
                            "incidents:write"
                        ]
                    }
                ]
            }
        },
        "/v1/incidents/secrets/{incident_id}/share": {
            "post": {
                "tags": [
                    "Secret Incidents"
                ],
                "operationId": "share-incident",
                "summary": "Share a secret incident",
                "description": "Share a secret incident by creating a public link.\n",
                "security": [
                    {
                        "APIKey": [
                            "incidents:share"
                        ]
                    }
                ]
            }
        },
        "/v1/incidents/secrets/{incident_id}/unshare": {
            "post": {
                "tags": [
                    "Secret Incidents"
                ],
                "operationId": "unshare-incident",
                "summary": "Unshare a secret incident",
                "description": "Unshare a secret incident by revoking its public link.\n",
                "security": [
                    {
                        "APIKey": [
                            "incidents:share"
                        ]
                    }
                ]
            }
        },
        "/v1/incidents/secrets/{incident_id}/grant_access": {
            "post": {
                "tags": [
                    "Secret Incidents"
                ],
                "operationId": "grant-access-incident",
                "summary": "Grant access to a secret incident",
                "description": "Grant a user, an existing invitee or a team access to a secret incident.\n",
                "security": [
                    {
                        "APIKey": [
                            "incidents:share"
                        ]
                    }
                ]
            }
        },
        "/v1/incidents/secrets/{incident_id}/revoke_access": {
            "post": {
                "tags": [
                    "Secret Incidents"
                ],
                "operationId": "revoke-access-incident",
                "summary": "Revoke access to a secret incident",
                "description": "Revoke access of a user, an existing invitee or a team to a secret incident.\n",
                "security": [
                    {
                        "APIKey": [
                            "incidents:share"
                        ]
                    }
                ]
            }
        },
        "/v1/incidents/secrets/{incident_id}/notes": {
            "get": {
                "tags": [
                    "Secret Incident Notes"
                ],
                "operationId": "list-incident-notes",
                "summary": "List notes on a secret incident",
                "description": "List notes left on a secret incident in chronological order.\n",
                "security": [
                    {
                        "APIKey": [
                            "incidents:read"
                        ]
                    }
                ]
            },
            "post": {
                "tags": [
                    "Secret Incident Notes"
                ],
                "operationId": "create-incident-note",
                "summary": "Create a secret incident note",
                "description": "Add a note on a secret incident.\n",
                "security": [
                    {
                        "APIKey": [
                            "incidents:write"
                        ]
                    }
                ]
            }
        },
        "/v1/incidents/secrets/{incident_id}/notes/{note_id}": {
            "patch": {
                "tags": [
                    "Secret Incident Notes"
                ],
                "operationId": "update-incident-note",
                "summary": "Update a secret incident note",
                "description": "Update an existing comment on a secret incident. Only incident notes\ncreated by the current API key can be updated.\n",
                "security": [
                    {
                        "APIKey": [
                            "incidents:write"
                        ]
                    }
                ]
            },
            "delete": {
                "tags": [
                    "Secret Incident Notes"
                ],
                "operationId": "delete-incident-note",
                "summary": "Delete a secret incident note",
                "description": "Delete an existing comment on a secret incident. Only incident notes\ncreated by the current API key can be deleted.\n",
                "security": [
                    {
                        "APIKey": [
                            "incidents:write"
                        ]
                    }
                ]
            }
        },
        "/v1/incidents/secrets/{incident_id}/members": {
            "get": {
                "tags": [
                    "Secret Incidents"
                ],
                "operationId": "list-incident-members",
                "summary": "List members having access to a secret incident",
                "description": "List all the members having access to a secret incident.\n",
                "security": [
                    {
                        "APIKey": [
                            "incidents:read",
                            "members:read"
                        ]
                    }
                ]
            }
        },
        "/v1/incidents/secrets/{incident_id}/teams": {
            "get": {
                "tags": [
                    "Secret Incidents"
                ],
                "operationId": "list-incident-teams",
                "summary": "List teams having access to a secret incident",
                "description": "List all the teams having access to a secret incident.\n",
                "security": [
                    {
                        "APIKey": [
                            "incidents:read",
                            "teams:read"
                        ]
                    }
                ]
            }
        },
        "/v1/incidents/secrets/{incident_id}/invitations": {
            "get": {
                "tags": [
                    "Secret Incidents"
                ],
                "operationId": "list-incident-invitations",
                "summary": "List invitations having access to a Secret Incident",
                "description": "List all the invitations having access to a Secret Incident.\n",
                "security": [
                    {
                        "APIKey": [
                            "incidents:read",
                            "members:read"
                        ]
                    }
                ]
            }
        },
        "/v1/occurrences/secrets": {
            "get": {
                "tags": [
                    "Secret Occurrences"
                ],
                "operationId": "list-occs",
                "summary": "List secret occurrences",
                "description": "List occurrences of secrets in the monitored perimeter.\n",
                "security": [
                    {
                        "APIKey": [
                            "incidents:read"
                        ]
                    }
                ]
            }
        },
        "/v1/invitations": {
            "get": {
                "tags": [
                    "Invitations"
                ],
                "operationId": "list-invitations",
                "summary": "List invitations",
                "description": "This endpoint allows you to list all pending invitations.\n\nThe response contains the list of invitations and a pagination cursor to retrieve the next page.\n\nThe invitations are sorted by id.\n\nIf you are using a personal access token, you need to have a role superior or equal to `member`.\n",
                "security": [
                    {
                        "APIKey": [
                            "members:read"
                        ]
                    }
                ]
            },
            "post": {
                "tags": [
                    "Invitations"
                ],
                "operationId": "create-invitations",
                "summary": "Create an invitation",
                "description": "This endpoint allows you to send an invitation to a user.\n\nIf you are using a personal access token, you need to have a role superior or equal to `member`.\n",
                "security": [
                    {
                        "APIKey": [
                            "members:write"
                        ]
                    }
                ]
            }
        },
        "/v1/invitations/{invitation_id}": {
            "delete": {
                "tags": [
                    "Invitations"
                ],
                "operationId": "delete-invitation",
                "summary": "Delete an invitation",
                "description": "Delete an existing invitation.\n\nIf you are using a personal access token, you need to have a role superior or equal to `manager`.\n",
                "security": [
                    {
                        "APIKey": [
                            "members:write"
                        ]
                    }
                ]
            }
        },
        "/v1/invitations/{invitation_id}/resend": {
            "post": {
                "tags": [
                    "Invitations"
                ],
                "operationId": "resend-invitation",
                "summary": "Resend an invitation",
                "description": "Resend an existing invitation.\n\nIf you are using a personal access token, you need to have a role superior or equal to `manager`.\n",
                "security": [
                    {
                        "APIKey": [
                            "members:write"
                        ]
                    }
                ]
            }
        },
        "/v1/members": {
            "get": {
                "tags": [
                    "Members"
                ],
                "operationId": "list-members",
                "summary": "List members",
                "description": "List members of the workspace.\n",
                "security": [
                    {
                        "APIKey": [
                            "members:read"
                        ]
                    }
                ]
            }
        },
        "/v1/members/{member_id}": {
            "get": {
                "tags": [
                    "Members"
                ],
                "operationId": "retrieve-member",
                "summary": "Retrieve a member",
                "description": "Retrieve an existing workspace member.\n\nIf you are using a personal access token, you need to have a role greater or equal to `member`.\n",
                "security": [
                    {
                        "APIKey": [
                            "members:read"
                        ]
                    }
                ]
            },
            "delete": {
                "tags": [
                    "Members"
                ],
                "operationId": "delete-member",
                "summary": "Delete a member",
                "description": "Delete an existing workspace member.\n\nIf you are using a personal access token, you need to have a role greater or equal to `manager`.\n",
                "security": [
                    {
                        "APIKey": [
                            "members:write"
                        ]
                    }
                ]
            },
            "patch": {
                "tags": [
                    "Members"
                ],
                "operationId": "update-member",
                "summary": "Update a member",
                "description": "Update an existing workspace member.\n\nIf you are using a personal access token, you need to have a role greater or equal to `manager`.\n",
                "security": [
                    {
                        "APIKey": [
                            "members:write"
                        ]
                    }
                ]
            }
        },
        "/v1/scan": {
            "post": {
                "tags": [
                    "Scan Methods"
                ],
                "operationId": "content_scan",
                "summary": "Content scan",
                "description": "Scan provided document content for policy breaks.\n\nRequest body shouldn't exceed 1MB.\n\nThis endpoint is stateless and as such will not store in our servers neither the documents nor the secrets found.\n",
                "security": [
                    {
                        "APIKey": [
                            "scan"
                        ]
                    }
                ]
            }
        },
        "/v1/multiscan": {
            "post": {
                "tags": [
                    "Scan Methods"
                ],
                "operationId": "multiple_scan",
                "summary": "Multiple content scan",
                "description": "Scan provided document contents for policy breaks.\nMultiple documents are returned by the same index order.\n\nThere should not be more than 20 documents in the payload. Individual documents should not exceed 1MB.\n\nQuota usage is based on requests and not on the content size. One request to this endpoint will consume 1 API call.\nAlso note that the quota is set on a rolling month and not on a calendar month.\nSee [this documentation](https://docs.gitguardian.co[...]",
                "security": [
                    {
                        "APIKey": [
                            "scan"
                        ]
                    }
                ]
            }
        },
        "/v1/secret_detectors": {
            "get": {
                "tags": [
                    "Secret Detectors"
                ],
                "operationId": "list-secret-detectors",
                "summary": "List secret detectors",
                "description": "List secret detectors.",
                "security": [
                    {
                        "APIKey": [
                            "incidents:read"
                        ]
                    }
                ]
            }
        },
        "/v1/secret_detectors/{detector_name}": {
            "get": {
                "tags": [
                    "Secret Detectors"
                ],
                "operationId": "get-secret-detector",
                "summary": "Get a secret detector",
                "description": "Get a secret detector.",
                "security": [
                    {
                        "APIKey": [
                            "incidents:read"
                        ]
                    }
                ]
            }
        },
        "/v1/quotas": {
            "get": {
                "tags": [
                    "Quota"
                ],
                "operationId": "quotas",
                "summary": "Quota overview",
                "description": "Check available scanning calls for this token. Quota is shared between all tokens of a workspace\n"
            }
        },
        "/v1/iac_scan": {
            "post": {
                "tags": [
                    "IaC Scan Methods"
                ],
                "operationId": "scan-iac",
                "summary": "Content scan",
                "description": "This feature is experimental.\n\nScan a tar file directory seeking potential IaC (Infrastructure as Code)\nvulnerabilities. Return a list of vulnerabilities found in the files\nof the scanned directory.\n",
                "security": [
                    {
                        "APIKey": [
                            "scan"
                        ]
                    }
                ]
            }
        },
        "/v1/iac_diff_scan": {
            "post": {
                "tags": [
                    "IaC Scan Methods"
                ],
                "operationId": "diff-scan-iac",
                "summary": "Differential scan",
                "description": "This feature is experimental.\n\nInfrastructure as Code (IaC) differential scanning compares two states of the\nsame project and reports any change in the vulnerabilities of your configuration.\n\nScan tar files containing two states of the same directory\n(under the names `reference` and `current`) seeking changes in potential\nIaC (Infrastructure as Code) vulnerabilities. Return the status of vulnerabilities\nfound in the files of the compared scanned directorie[...]",
                "security": [
                    {
                        "APIKey": [
                            "scan"
                        ]
                    }
                ]
            }
        },
        "/v1/sources": {
            "get": {
                "tags": [
                    "Sources"
                ],
                "operationId": "list-sources",
                "summary": "List sources",
                "description": "List vcs sources monitored by GitGuardian.\n",
                "security": [
                    {
                        "APIKey": [
                            "incidents:read"
                        ]
                    }
                ]
            }
        },
        "/v1/sources/{source_id}": {
            "get": {
                "tags": [
                    "Sources"
                ],
                "operationId": "retrieve-source",
                "summary": "Retrieve a source",
                "description": "Retrieve a source monitored by GitGuardian.\n",
                "security": [
                    {
                        "APIKey": [
                            "incidents:read"
                        ]
                    }
                ]
            }
        },
        "/v1/audit_logs": {
            "get": {
                "tags": [
                    "Audit Logs"
                ],
                "operationId": "list-audit-logs",
                "summary": "List audit Logs",
                "description": "List audit logs.",
                "security": [
                    {
                        "APIKey": [
                            "audit_logs:read"
                        ]
                    }
                ]
            }
        },
        "/v1/health": {
            "get": {
                "tags": [
                    "Status"
                ],
                "operationId": "health_check",
                "summary": "Health check",
                "description": "Check the status of the API and your token without spending your quota."
            }
        },
        "/v1/teams": {
            "get": {
                "tags": [
                    "Teams"
                ],
                "operationId": "list-teams",
                "summary": "List teams",
                "description": "This endpoint allows you to list all the teams of your workspace.\n\nThe response contains the list of teams and a pagination cursor to retrieve the next page.\n\nThe teams are sorted by id.\n\nIf you are using a personal access token, you need to have a role superior or equal to `member`.\n",
                "security": [
                    {
                        "APIKey": [
                            "teams:read"
                        ]
                    }
                ]
            },
            "post": {
                "tags": [
                    "Teams"
                ],
                "operationId": "create-teams",
                "summary": "Create a team",
                "description": "This endpoint allows you to create a team.\n\nIf you are using a personal access token, you need to have a role superior or equal to `manager`.\n\nIf a personal access token is being used, the member is automatically added to the created team with permissions `can_manage` and `full_access`\n",
                "security": [
                    {
                        "APIKey": [
                            "teams:write"
                        ]
                    }
                ]
            }
        },
        "/v1/teams/{team_id}": {
            "get": {
                "tags": [
                    "Teams"
                ],
                "operationId": "retrieve-team",
                "summary": "Retrieve a team",
                "description": "Retrieve an existing team.\n\nIf you are using a personal access token, you need to have a role greater or equal to `member`.\n",
                "security": [
                    {
                        "APIKey": [
                            "teams:read"
                        ]
                    }
                ]
            },
            "delete": {
                "tags": [
                    "Teams"
                ],
                "operationId": "delete-team",
                "summary": "Delete a team",
                "description": "Delete an existing team.\n\nIf you are using a personal access token, you must have \"can manage\" permission on the team or be a workspace manager.\n\nThe \"All-incidents\" team (is_global=true) cannot be deleted.\n",
                "security": [
                    {
                        "APIKey": [
                            "teams:write"
                        ]
                    }
                ]
            },
            "patch": {
                "tags": [
                    "Teams"
                ],
                "operationId": "update-team",
                "summary": "Update a team",
                "description": "Update a team's name and/or its description.\n\nIf you are using a personal access token, you must have \"can manage\" permission on the team or be a workspace manager.\n\nThe \"All-incidents\" team (is_global=true) cannot be updated.\n",
                "security": [
                    {
                        "APIKey": [
                            "teams:write"
                        ]
                    }
                ]
            }
        },
        "/v1/teams/{team_id}/incidents/secrets": {
            "get": {
                "tags": [
                    "Secret Incidents",
                    "Teams"
                ],
                "operationId": "list-team-incidents",
                "summary": "List secret incidents of a team",
                "description": "List secret incidents of a particular team.\nOccurrences are not returned in this route.\n",
                "security": [
                    {
                        "APIKey": [
                            "incidents:read",
                            "teams:read"
                        ]
                    }
                ]
            }
        },
        "/v1/members/{member_id}/teams": {
            "get": {
                "tags": [
                    "Members"
                ],
                "operationId": "list-member-teams",
                "summary": "List teams of a member",
                "description": "List teams of a workspace member.\nThe response contains the list of teams and a pagination cursor to retrieve the next page.\n\nThe teams are sorted by id.\n\nIf you are using a personal access token, you need to have a role superior or equal to `manager` except if the requested member is yourself.\n",
                "security": [
                    {
                        "APIKey": [
                            "members:read",
                            "teams:read"
                        ]
                    }
                ]
            }
        },
        "/v1/teams/{team_id}/team_invitations": {
            "get": {
                "tags": [
                    "Team Invitations"
                ],
                "operationId": "list-team-invitation",
                "summary": "List team invitations",
                "description": "List all existing team invitations.\n\nIf you are using a personal access token, you must have \"can manage\" permission on the team or be a workspace manager.\n",
                "security": [
                    {
                        "APIKey": [
                            "teams:read"
                        ]
                    }
                ]
            },
            "post": {
                "tags": [
                    "Team Invitations"
                ],
                "operationId": "create-team-invitations",
                "summary": "Create a team invitation",
                "description": "This endpoint allows you to create a team invitation from an existing team and invitation.\n\nIf you are using a personal access token, you must have \"can manage\" permission on the team or be a workspace manager.\n",
                "security": [
                    {
                        "APIKey": [
                            "teams:write"
                        ]
                    }
                ]
            }
        },
        "/v1/teams/{team_id}/team_invitations/{team_invitation_id}": {
            "patch": {
                "tags": [
                    "Team Invitations"
                ],
                "operationId": "update-team-invitation",
                "summary": "Update a team invitation",
                "description": "Update permissions of a team invitation.\n\nIf you are using a personal access token, you must have \"can manage\" permission on the team or be a workspace manager.\n",
                "security": [
                    {
                        "APIKey": [
                            "teams:write"
                        ]
                    }
                ]
            },
            "delete": {
                "tags": [
                    "Team Invitations"
                ],
                "operationId": "delete-team-invitation",
                "summary": "Delete a team invitation",
                "description": "Delete an existing team invitation.\n\nIf you are using a personal access token, you must have \"can manage\" permission on the team or be a workspace manager.\n",
                "security": [
                    {
                        "APIKey": [
                            "teams:write"
                        ]
                    }
                ]
            }
        },
        "/v1/teams/{team_id}/team_memberships": {
            "get": {
                "tags": [
                    "Team Memberships"
                ],
                "operationId": "list-team-memberships",
                "summary": "List team memberships",
                "description": "List all the memberships of a team.\n\nIf you are using a personal access token, you need to be a workspace manager or be part of the team.\n",
                "security": [
                    {
                        "APIKey": [
                            "teams:read"
                        ]
                    }
                ]
            },
            "post": {
                "tags": [
                    "Team Memberships"
                ],
                "operationId": "create-team-membership",
                "summary": "Add a member to a team",
                "description": "Add a member to a team.\n\nIf you are using a personal access token, you must have \"can manage\" permission on the team or be a workspace manager.\n",
                "security": [
                    {
                        "APIKey": [
                            "teams:write"
                        ]
                    }
                ]
            }
        },
        "/v1/teams/{team_id}/team_memberships/{team_membership_id}": {
            "patch": {
                "tags": [
                    "Team Memberships"
                ],
                "operationId": "update-team-membership",
                "summary": "Update a team membership",
                "description": "Update permissions of a team membership.\n\nIf you are using a personal access token, you must have \"can manage\" permission on the team or be a workspace manager.\n",
                "security": [
                    {
                        "APIKey": [
                            "teams:write"
                        ]
                    }
                ]
            },
            "delete": {
                "tags": [
                    "Team Memberships"
                ],
                "operationId": "delete-team-membership",
                "summary": "Remove a member from a team",
                "description": "Remove a member from a team.\n\nIf you are using a personal access token, you must have \"can manage\" permission on the team or be a workspace manager,\nor be the member being removed.\n",
                "security": [
                    {
                        "APIKey": [
                            "teams:write"
                        ]
                    }
                ]
            }
        },
        "/v1/members/{member_id}/team_memberships": {
            "get": {
                "tags": [
                    "Members"
                ],
                "operationId": "list-member-team-memberships",
                "summary": "List team memberships of a member",
                "description": "List team memberships of a workspace member.\nThe response contains the list of team memberships and a pagination cursor to retrieve the next page.\n\nThe team memberships are sorted by id.\n\nIf you are using a personal access token, you need to have a role superior or equal to `manager` except if the requested member is yourself.\n",
                "security": [
                    {
                        "APIKey": [
                            "members:read"
                        ]
                    }
                ]
            }
        },
        "/v1/teams/{team_id}/team_requests": {
            "get": {
                "tags": [
                    "Team Requests"
                ],
                "operationId": "list-team-requests",
                "summary": "List team requests of a team",
                "description": "List pending requests of a team.\n\nIf you are using a personal access token, you must have \"can manage\" permission on the team or be a workspace manager.\n",
                "security": [
                    {
                        "APIKey": [
                            "teams:read"
                        ]
                    }
                ]
            },
            "post": {
                "tags": [
                    "Team Requests"
                ],
                "operationId": "create-team-request",
                "summary": "Request access to a team",
                "description": "Create an access request to a team.\n\nYou must be authenticated via a Personal Access Token. You must not already have a pending\nrequest on the team, be a member of the team, be a workspace manager or have the\nrestricted role.\n",
                "security": [
                    {
                        "APIKey": [
                            "teams:write"
                        ]
                    }
                ]
            }
        },
        "/v1/teams/{team_id}/team_requests/{team_request_id}": {
            "delete": {
                "tags": [
                    "Team Requests"
                ],
                "operationId": "delete-team-request",
                "summary": "Cancel or decline a team request",
                "description": "Cancel or decline a team request.\n\nIf you are using a personal access token, you must have \"can manage\" permission on the team or be a workspace manager, or\nbe the member who created the request being cancelled.\n",
                "security": [
                    {
                        "APIKey": [
                            "teams:write"
                        ]
                    }
                ]
            }
        },
        "/v1/teams/{team_id}/team_requests/{team_request_id}/accept": {
            "post": {
                "tags": [
                    "Team Requests"
                ],
                "operationId": "accept-team-request",
                "summary": "Accept a team request",
                "description": "Accept a team request by adding the member to the team.\n\nIf you are using a personal access token, you must have \"can manage\" permission on the team or be a workspace manager.\n",
                "security": [
                    {
                        "APIKey": [
                            "teams:write"
                        ]
                    }
                ]
            }
        },
        "/v1/members/{member_id}/team_requests": {
            "get": {
                "tags": [
                    "Team Requests"
                ],
                "operationId": "list-member-team-requests",
                "summary": "List team requests of a member",
                "description": "List pending team requests of a member.\n\nIf you are using a personal access token, you need to be either a workspace manager or the member being queried.\n",
                "security": [
                    {
                        "APIKey": [
                            "members:read",
                            "teams:read"
                        ]
                    }
                ]
            }
        },
        "/v1/teams/{team_id}/sources": {
            "get": {
                "tags": [
                    "Team Sources"
                ],
                "operationId": "list-team-sources",
                "summary": "List team sources",
                "description": "List sources belonging to a team's perimeter.\n",
                "security": [
                    {
                        "APIKey": [
                            "teams:read"
                        ]
                    }
                ]
            },
            "post": {
                "tags": [
                    "Team Sources"
                ],
                "operationId": "update-team-sources",
                "summary": "Update a team perimeter",
                "description": "This endpoint allows you to add and remove sources from the perimeter of a team.\n\nIf you are using a personal access token, you need to be a workspace manager.\n",
                "security": [
                    {
                        "APIKey": [
                            "teams:write"
                        ]
                    }
                ]
            }
        },
        "/v1/honeytokens": {
            "get": {
                "tags": [
                    "Honeytokens"
                ],
                "operationId": "list-honeytoken",
                "summary": "List honeytokens",
                "description": "This endpoint allows you to list all the honeytokens of your workspace.\n\nThe response contains the list of honeytokens and a pagination cursor to retrieve the next page.\n\nThe honeytokens are sorted by id.\n\nIf you are using a personal access token, you need to have a role superior or equal to `manager`.\n",
                "security": [
                    {
                        "APIKey": [
                            "honeytokens:read"
                        ]
                    }
                ]
            },
            "post": {
                "tags": [
                    "Honeytokens"
                ],
                "operationId": "create-honeytoken",
                "summary": "Create a honeytoken",
                "description": "This endpoint allows you to create a honeytoken of a type.\n\nIf you are using a personal access token, you need to have a role superior or equal to `manager`.\n",
                "security": [
                    {
                        "APIKey": [
                            "honeytokens:write"
                        ]
                    }
                ]
            }
        },
        "/v1/honeytokens/{honeytoken_id}": {
            "get": {
                "tags": [
                    "Honeytokens"
                ],
                "operationId": "retrieve-honeytoken",
                "summary": "Retrieve a honeytoken",
                "description": "Retrieve an existing honeytoken.\n\nIf you are using a personal access token, you need to have a role greater or equal to `manager`.\n",
                "security": [
                    {
                        "APIKey": [
                            "honeytokens:read"
                        ]
                    }
                ]
            },
            "patch": {
                "tags": [
                    "Honeytokens"
                ],
                "operationId": "update-honeytoken",
                "summary": "Update a honeytoken",
                "description": "Update a name or descriptions of an existing honeytoken.\n",
                "security": [
                    {
                        "APIKey": [
                            "honeytokens:write"
                        ]
                    }
                ]
            }
        },
        "/v1/honeytokens/{honeytoken_id}/reset": {
            "post": {
                "tags": [
                    "Honeytokens"
                ],
                "operationId": "reset-honeytoken",
                "summary": "Reset the honeytoken",
                "description": "Resets a triggered honeytoken. All the associated events will be closed.\n",
                "security": [
                    {
                        "APIKey": [
                            "honeytokens:write"
                        ]
                    }
                ]
            }
        },
        "/v1/honeytokens/{honeytoken_id}/revoke": {
            "post": {
                "tags": [
                    "Honeytokens"
                ],
                "operationId": "revoke-honeytoken",
                "summary": "Revoke the honeytoken",
                "description": "Revokes an active or triggered honeytoken. All the associated events will be closed.\n",
                "security": [
                    {
                        "APIKey": [
                            "honeytokens:write"
                        ]
                    }
                ]
            }
        },
        "/v1/honeytokens/{honeytoken_id}/notes": {
            "get": {
                "tags": [
                    "Honeytoken Notes"
                ],
                "operationId": "list-honeytoken-notes",
                "summary": "List notes on an honeytoken",
                "description": "List notes left on a honeytoken in chronological order.\n",
                "security": [
                    {
                        "APIKey": [
                            "honeytokens:read"
                        ]
                    }
                ]
            },
            "post": {
                "tags": [
                    "Honeytoken Notes"
                ],
                "operationId": "create-honeytoken-note",
                "summary": "Create an honeytoken note",
                "description": "Add a note on a honeytoken.\n",
                "security": [
                    {
                        "APIKey": [
                            "honeytokens:write"
                        ]
                    }
                ]
            }
        },
        "/v1/honeytokens/{honeytoken_id}/notes/{note_id}": {
            "patch": {
                "tags": [
                    "Honeytoken Notes"
                ],
                "operationId": "update-honeytoken-note",
                "summary": "Update a honeytoken note",
                "description": "Update an existing comment on a honeytoken. Only honeytoken notes\ncreated by the current API key can be updated.\n",
                "security": [
                    {
                        "APIKey": [
                            "honeytokens:write"
                        ]
                    }
                ]
            },
            "delete": {
                "tags": [
                    "Honeytoken Notes"
                ],
                "operationId": "delete-honeytoken-note",
                "summary": "Delete a honeytoken note",
                "description": "Delete an existing comment on a honeytoken. Only honeytoken notes\ncreated by the current API key can be deleted.\n",
                "security": [
                    {
                        "APIKey": [
                            "honeytokens:write"
                        ]
                    }
                ]
            }
        },
        "/v1/honeytokens/{honeytoken_id}/sources": {
            "get": {
                "tags": [
                    "Honeytoken Sources"
                ],
                "operationId": "list-honeytoken-sources",
                "summary": "List sources on an honeytoken",
                "description": "List sources where a honeytoken appears.\n",
                "security": [
                    {
                        "APIKey": [
                            "honeytokens:read"
                        ]
                    }
                ]
            }
        },
        "/v1/honeytokens_events": {
            "get": {
                "tags": [
                    "Honeytokens Events"
                ],
                "operationId": "list-honeytokens-events",
                "summary": "List all honeytokens events",
                "description": "List events related to all honeytokens of the workspace.\n",
                "security": [
                    {
                        "APIKey": [
                            "honeytokens:read"
                        ]
                    }
                ]
            }
        },
        "/v1/honeytokens/labels": {
            "get": {
                "tags": [
                    "Labels"
                ],
                "operationId": "list-honeytoken-labels",
                "summary": "List labels",
                "description": "List labels created for honeytokens in chronological order.\n",
                "security": [
                    {
                        "APIKey": [
                            "honeytokens:read"
                        ]
                    }
                ]
            },
            "post": {
                "tags": [
                    "Labels"
                ],
                "operationId": "create-honeytoken-label",
                "summary": "Create a label",
                "description": "Create a label for honeytokens.\n",
                "security": [
                    {
                        "APIKey": [
                            "honeytokens:write"
                        ]
                    }
                ]
            },
            "patch": {
                "tags": [
                    "Labels"
                ],
                "operationId": "patch-honeytoken-label-key",
                "summary": "Update a key",
                "description": "Rename a label key. It will be renamed in all the labels using this key.\n",
                "security": [
                    {
                        "APIKey": [
                            "honeytokens:write"
                        ]
                    }
                ]
            },
            "delete": {
                "tags": [
                    "Labels"
                ],
                "operationId": "delete-honeytoken-label-key",
                "summary": "Delete a key",
                "description": "Delete a key. All the labels using this key will be deleted.\n",
                "security": [
                    {
                        "APIKey": [
                            "honeytokens:write"
                        ]
                    }
                ]
            }
        },
        "/v1/honeytokens/labels/{label_id}": {
            "patch": {
                "tags": [
                    "Labels"
                ],
                "operationId": "patch-honeytoken-label",
                "summary": "Update a value",
                "description": "Rename the value of a label.\n",
                "security": [
                    {
                        "APIKey": [
                            "honeytokens:write"
                        ]
                    }
                ]
            },
            "delete": {
                "tags": [
                    "Labels"
                ],
                "operationId": "delete-honeytoken-label",
                "summary": "Delete a label",
                "description": "Delete a label for honeytokens.\n",
                "security": [
                    {
                        "APIKey": [
                            "honeytokens:write"
                        ]
                    }
                ]
            }
        },
        "/v1/sca/compute_sca_files": {
            "get": {
                "tags": [
                    "SCA"
                ],
                "operationId": "compute-sca-files",
                "summary": "Compute SCA files amongst a list of files.",
                "description": "Compute SCA files amongst a list of files.",
                "security": [
                    {
                        "APIKey": [
                            "scan"
                        ]
                    }
                ]
            }
        },
        "/v1/sca/sca_scan_all": {
            "post": {
                "operationId": "sca-scan-all",
                "description": "Scan a directory using GitGuardian SCA engine",
                "summary": "Scan a directory using GitGuardian SCA engine",
                "tags": [
                    "SCA"
                ]
            }
        },
        "/v1/sca/sca_scan_diff": {
            "post": {
                "operationId": "sca-scan-diff",
                "description": "Scan a diff using GitGuardian SCA engine",
                "summary": "Scan a diff using GitGuardian SCA engine",
                "tags": [
                    "SCA"
                ]
            }
        }
    },
    "components": {
        "securitySchemes": {
            "APIKey": {
                "description": "Usage: `Token <API Key>` in `Authorization` header.\n",
                "type": "http",
                "scheme": "bearer",
                "bearerFormat": "Token <API Key>"
            }
        }
    },
    "security": [
        {
            "APIKey": []
        }
    ]
}